name: Claude Code

on:
  issue_comment:
    types: [created]
  issues:
    types: [opened]

jobs:
  claude:
    if: contains(github.event.comment.body, '@claude') || contains(github.event.issue.body, '@claude')
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Claude Code
        uses: anthropics/anthropic-quickstarts@claude-code-v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
